BUILD_PATH = ../build
SRC_PATH = ""

LDLIBS = -lboost_program_options
PATHLIB = /usr/include/boost
CXX = g++
CXXFLAGS += -std=c++17 -O3 -Wall
LDFLAGS = -L$(PATHLIB) $(LDLIBS)

DEPS = $(shell find $(SRC_PATH)core $(SRC_PATH)simulator -name '*.h')
OBJ = $(DEPS:.h=.o) $(MAIN).o
